//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey_converter.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survey_converter.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AddDataCommandText.
        /// </summary>
        public static string AddDataCommandText {
            get {
                return ResourceManager.GetString("AddDataCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ConvertButtonText.
        /// </summary>
        public static string ConvertButtonText {
            get {
                return ResourceManager.GetString("ConvertButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ConvertCommandsText.
        /// </summary>
        public static string ConvertCommandsText {
            get {
                return ResourceManager.GetString("ConvertCommandsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FileDialog.
        /// </summary>
        public static string FileDialog {
            get {
                return ResourceManager.GetString("FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FileDialogText.
        /// </summary>
        public static string FileDialogText {
            get {
                return ResourceManager.GetString("FileDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FinalizationCommandText.
        /// </summary>
        public static string FinalizationCommandText {
            get {
                return ResourceManager.GetString("FinalizationCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на get_FolderWithSignals_Exeption.
        /// </summary>
        public static string get_FolderWithSignals_Exeption {
            get {
                return ResourceManager.GetString("get_FolderWithSignals_Exeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information about signals:.
        /// </summary>
        public static string InformationAboutSignalsText {
            get {
                return ResourceManager.GetString("InformationAboutSignalsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InitializationCommandText.
        /// </summary>
        public static string InitializationCommandText {
            get {
                return ResourceManager.GetString("InitializationCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing_FS_instance.
        /// </summary>
        public static string Missing_FS_instance_Exeption {
            get {
                return ResourceManager.GetString("Missing_FS_instance_Exeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на process_DesiarializationFailed_Exeption.
        /// </summary>
        public static string process_DesiarializationFailed_Exeption {
            get {
                return ResourceManager.GetString("process_DesiarializationFailed_Exeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProgressOfConvertionText.
        /// </summary>
        public static string ProgressOfConvertionText {
            get {
                return ResourceManager.GetString("ProgressOfConvertionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ResetCommandText.
        /// </summary>
        public static string ResetCommandText {
            get {
                return ResourceManager.GetString("ResetCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SaveFolderPathWatermark.
        /// </summary>
        public static string SaveFolderPathWatermark {
            get {
                return ResourceManager.GetString("SaveFolderPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SaveFolderTitle.
        /// </summary>
        public static string SaveFolderTitle {
            get {
                return ResourceManager.GetString("SaveFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SelectFormatText.
        /// </summary>
        public static string SelectFormatText {
            get {
                return ResourceManager.GetString("SelectFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ToCSV.
        /// </summary>
        public static string ToCSV {
            get {
                return ResourceManager.GetString("ToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ToEDF.
        /// </summary>
        public static string ToEDF {
            get {
                return ResourceManager.GetString("ToEDF", resourceCulture);
            }
        }
    }
}
